### ISSUE TITLE
[Bug] Strange error after trying to do /reload on the server

### ISSUE THREAD

**Issue by vico93** [Jagenka/DisKordel#106]
Got this error and cant reload my datapacks with the command `/reload`:

```
[18:42:46] [Server thread/WARN]: Failed to execute reload
java.util.concurrent.CompletionException: java.lang.IllegalStateException: command id `whois` is already assigned to command de.jagenka.commands.universal.WhoisCommand@2e963b84
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1194) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309) ~[?:?]
        at net.minecraft.server.MinecraftServer.method_29439(MinecraftServer.java:1319) ~[server-intermediary.jar:?]
        at net.minecraft.class_3097.method_29480(class_3097.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3097.method_13530(class_3097.java:53) ~[server-intermediary.jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.1.8.jar:?]
        at net.minecraft.class_2170.redirect$zbc000$architectury$performCommand(class_2170.java:545) ~[server-intermediary.jar:?]
        at net.minecraft.class_2170.method_9249(class_2170.java:287) ~[server-intermediary.jar:?]
        at net.minecraft.class_2170.method_44252(class_2170.java:280) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_13941(class_3176.java:299) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:284) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: command id `whois` is already assigned to command de.jagenka.commands.universal.WhoisCommand@2e963b84
        at de.jagenka.commands.discord.structure.Registry.register(Registry.kt:72) ~[diskordel-3.3.0-1.20.1.jar:?]
        at de.jagenka.commands.universal.StringInStringOutCommand$DefaultImpls.register(StringInStringOutCommand.kt:24) ~[diskordel-3.3.0-1.20.1.jar:?]
        at de.jagenka.commands.universal.WhoisCommand.register(WhoisCommand.kt:7) ~[diskordel-3.3.0-1.20.1.jar:?]
        at de.jagenka.Main.onInitialize$lambda$2(Main.kt:48) ~[diskordel-3.3.0-1.20.1.jar:?]
        at net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:43) ~[fabric-command-api-v2-2.2.12+b3afc78b77-cf6a12d51d27b247.jar:?]
        at net.minecraft.class_2170.handler$zme000$fabric-command-api-v2$fabric_addCommands(class_2170.java:1048) ~[server-intermediary.jar:?]
        at net.minecraft.class_2170.<init>(class_2170.java:267) ~[server-intermediary.jar:?]
        at net.minecraft.class_5350.<init>(class_5350.java:43) ~[server-intermediary.jar:?]
        at net.minecraft.class_5350.method_29466(class_5350.java:73) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29437(MinecraftServer.java:1321) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) ~[?:?]
        ... 14 more
[18:42:46] [Server thread/INFO]: Reload failed; keeping old data
```

**Comment by Jagenka** [comment]
no longer reproducable on newest version
