### ISSUE TITLE
ConcurrentModificationException on some launches

### ISSUE THREAD

**Issue by Jagenka** [Jagenka/DisKordel#83]
```
[DefaultDispatcher-worker-17 @coroutine#67/ERROR] (FabricLoader) Uncaught exception in thread "DefaultDispatcher-worker-17 @coroutine#67"
 java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756) ~[?:?]
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:778) ~[?:?]
	at de.jagenka.UserRegistry.saveCacheToFile(UserRegistry.kt:280) ~[main/:?]
	at de.jagenka.UserRegistry$findMinecraftProfileOrError$1.onProfileLookupSucceeded(UserRegistry.kt:234) ~[main/:?]
	at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:64) ~[authlib-4.0.43.jar:?]
	at de.jagenka.UserRegistry.findMinecraftProfileOrError(UserRegistry.kt:226) ~[main/:?]
	at de.jagenka.UserRegistry.register(UserRegistry.kt:106) ~[main/:?]
	at de.jagenka.UserRegistry$register$2.invokeSuspend(UserRegistry.kt:140) ~[main/:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.8.21.jar:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.7.1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584) ~[kotlinx-coroutines-core-jvm-1.7.1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793) ~[kotlinx-coroutines-core-jvm-1.7.1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697) ~[kotlinx-coroutines-core-jvm-1.7.1.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684) ~[kotlinx-coroutines-core-jvm-1.7.1.jar:?]
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException
```

**Comment by Jagenka** [comment]
might be, because `UserRegistry::loadUserCache` uses forEach on `minecraftProfiles` and `findMinecraftProfileOrError` adds to `minecraftProfiles`

**Comment by Jagenka** [comment]
should be fixed in https://github.com/Jagenka/DisKordel/releases/tag/v3.2.0-1.20.1
